name: regionmask
channels:
  - scitools
  - conda-forge
dependencies:
  - python=3.6
  - numpydoc
  - ipython
  - cartopy
  - geopandas
  - xarray
  - jupyter
  - nbconvert
  - pip:
    - regionmask 
