name: regionmask-docs
channels:
  - conda-forge
dependencies:
  - python=3.7
  - cartopy=0.17.0
  - numpydoc=0.9.1
  - ipython=7.8.0
  - geopandas=0.5.1
  - xarray=0.13
  - jupyter=1.0.0
  - nbconvert=5.6.0
  - pip=19.2
  - netcdf4=1.5
  - cftime=1.0.3.4
  - nc-time-axis
  # - pip:
  #   - netcdf4
  #   - geopandas
  #   - xarray=0.13
  #   - numpydoc
  #   - nbconvert
  #   - jupyter
  #   - ipython
